### ISSUE TITLE
Заполнение инструктора в прыжке

### ISSUE THREAD

**Issue by Konfeta3-33** [Konfeta3-33/SD_Dubai#31]
- В policy добавить метод `edit_instructor? = admin?`
- Во форме реализовать следующую логику
  - если у пользователя есть право edit_instructor? - отображать select с инструкторами, где выбранным делать инструктора из прыжка, если он заполнен
  - если у пользователя нет права на изменение инструктора и у прыжка инструктор не заполнен - подставить инструктора из текущего пользователя
  - если в прыжке заполнен инструктор - отображать из прыжка

**Comment by skyksandr** [comment]
fixed in #51
