### ISSUE TITLE
Тип "Tunnel" между тандемом и Cat A

### ISSUE THREAD

**Issue by skyksandr** [Konfeta3-33/SD_Dubai#35]
[templates.pdf](https://github.com/Konfeta3-33/SD_Dubai/files/9286734/templates.pdf)

<img width="470" alt="image" src="https://user-images.githubusercontent.com/5262979/183564100-fbed1465-13fc-40d9-82e8-1c7917989a65.png">

**Comment by Konfeta3-33** [comment]
Done
