### ISSUE TITLE
Форма категории "C1" и "C2" (они одинаковые)

### ISSUE THREAD

**Issue by skyksandr** [Konfeta3-33/SD_Dubai#37]
[templates.pdf](https://github.com/Konfeta3-33/SD_Dubai/files/9286926/templates.pdf)

<img width="474" alt="image" src="https://user-images.githubusercontent.com/5262979/183568658-ef48cec1-6d3e-47c8-a80d-369bd6f5e619.png">

**Comment by Konfeta3-33** [comment]
done
