### ISSUE TITLE
Печатная версия страницы прыжка

### ISSUE THREAD

**Issue by skyksandr** [Konfeta3-33/SD_Dubai#42]

**Comment by Konfeta3-33** [comment]
- Category A - done

**Comment by Konfeta3-33** [comment]
- Category D1 - done

**Comment by Konfeta3-33** [comment]
- Category B - done
 - Category C1 - done
 - Category C2 - done

**Comment by Konfeta3-33** [comment]
- Category D2 - done

**Comment by Konfeta3-33** [comment]
- category E1 - done
- category E2 - done
