### ISSUE TITLE
Display instructor license

### ISSUE THREAD

**Issue by skyksandr** [Konfeta3-33/SD_Dubai#59]
Implementation plan:
- replace `collection_select` with `select` + `options_for_select` where provide `data-license` and `data-initials` attributes
- (maybe) extract the code to helper method
- setup `jsbundling-rails` using `esbuild`
- Add stimulus to the app
- Create stimulus controller for instructor fields, add select and license as targets
- On controller connect update license, setup listeners to change events if select is present and update license on change

**Comment by Konfeta3-33** [comment]
done
