### ISSUE TITLE
Total freefall time not saving in "MM:SS" format

### ISSUE THREAD

**Issue by skyksandr** [Konfeta3-33/SD_Dubai#77]
If input this:
![image](https://user-images.githubusercontent.com/5262979/186061787-27818f77-9c1c-46a6-b2a4-e3f1ffe8ff33.png)

After save:
![image](https://user-images.githubusercontent.com/5262979/186061871-65242732-038d-4942-b7f8-5b752ea342cd.png)

**Comment by Konfeta3-33** [comment]
Done
